TeamsDict =	{
	"Milwaukee Bucks" : "MIL",
	"Golden State Warriors" : "GSW",
	"New Orleans Pelicans" : "NOP",
	"Philadelphia 76ers" : "PHI",
	"Los Angeles Clippers" : "LAC",
	"Portland Trail Blazers" : "POR",
	"Oklahoma City Thunder" : "OKC",
	"Toronto Raptors" : "TOR",
	"Sacramento Kings" : "SAC",
	"Washington Wizards" : "WAS",
	"Houston Rockets" : "HOU",
	"Atlanta Hawks" : "ATL",
	"Minnesota Timberwolves" : "MIN",
	"Boston Celtics" : "BOS",
	"Brooklyn Nets" : "BRK",
	"Los Angeles Lakers" : "LAL",
	"Utah Jazz" : "UTA",
	"San Antonio Spurs" : "SAS",
	"Charlotte Hornets" : "CHO",
	"Denver Nuggets" : "DEN",
	"Dallas Mavericks" : "DAL",
	"Indiana Pacers" : "IND",
	"Phoenix Suns" : "PHO",
	"Orlando Magic" : "ORL",
	"Detroit Pistons" : "DET",
	"Miami Heat" : "MIA",
	"Chicago Bulls" : "CHI",
	"New York Knicks" : "NYK",
	"Cleveland Cavaliers" : "CLE",
	"Memphis Grizzlies" : "MEM"
}
